# AUTO-GENERATED by skill-architect (signal: GAP-20260408-001)
# Created: 2026-04-08T00:00:00Z
# DO NOT EDIT MANUALLY — re-run skill-architect to regenerate
"""Margin exhaustion score — 선물 포지션 청산 임박도를 0~1로 환산.

Pure analytical primitive. Wraps position_math.realized_pnl_simple for
unrealized PnL and computes liquidation distance assuming isolated margin
with configurable maintenance margin rate.

Trust anchor: backend/app/core/position_math.py (human-reviewed).
No other AI-generated skills are imported.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from pathlib import Path
from typing import Any, Dict

# ─── Bootstrap: backend on sys.path for app.core.* imports ───────────────
_SCRIPT_DIR = Path(__file__).parent
_BACKEND_DIR = _SCRIPT_DIR.parent.parent.parent.parent / "backend"
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

from app.core.position_math import realized_pnl_simple  # noqa: E402

SKILL_NAME = "at-monitor/margin_exhaustion"
SKILL_VERSION = "0.1.0"

# Default Binance futures maintenance margin rate (0.5%)
DEFAULT_MMR = 0.005


def compute_exhaustion(
    cash: float,
    qty: int,
    avg_cost: float,
    current_price: float,
    leverage: int,
    side: str,
    maintenance_margin_rate: float = DEFAULT_MMR,
) -> Dict[str, Any]:
    """Compute margin exhaustion score for a single futures position.

    Score interpretation:
      0.0 → plenty of margin, safe
      1.0 → at or past liquidation threshold

    Isolated margin assumption:
      - initial_margin = (notional / leverage)
      - maintenance_margin = notional * mmr
      - liquidation when (initial_margin + unrealized_pnl) <= maintenance_margin

    The liquidation price for a LONG position (isolated):
      liq_price = avg_cost * (1 - 1/leverage + mmr)

    For SHORT:
      liq_price = avg_cost * (1 + 1/leverage - mmr)
    """
    if qty == 0 or avg_cost <= 0 or current_price <= 0 or leverage <= 0:
        return {
            "exhaustion_score": 0.0,
            "liquidation_distance_pct": 0.0,
            "unrealized_pnl": 0.0,
            "margin_ratio": 0.0,
            "reason": "no_position_or_invalid_inputs",
        }

    abs_qty = abs(qty)
    side_norm = side.lower()

    # Unrealized PnL via shared math
    unrealized = realized_pnl_simple(side_norm, avg_cost, current_price, abs_qty)

    # Notional + margin calculations
    notional_entry = avg_cost * abs_qty
    initial_margin = notional_entry / leverage
    maintenance_margin = notional_entry * maintenance_margin_rate

    # Remaining equity in the position = initial_margin + unrealized_pnl
    remaining_equity = initial_margin + unrealized

    # Margin ratio: 1.0 = exactly at maintenance, > 1.0 = safe buffer
    if maintenance_margin > 0:
        margin_ratio = remaining_equity / maintenance_margin
    else:
        margin_ratio = float("inf")

    # Liquidation price (isolated margin, simplified, no fees)
    if side_norm == "long":
        liq_price = avg_cost * (1 - 1 / leverage + maintenance_margin_rate)
        distance = (current_price - liq_price) / avg_cost
    else:  # short
        liq_price = avg_cost * (1 + 1 / leverage - maintenance_margin_rate)
        distance = (liq_price - current_price) / avg_cost

    # Entry distance = initial cushion from entry to liquidation
    if side_norm == "long":
        entry_distance = (avg_cost - liq_price) / avg_cost
    else:
        entry_distance = (liq_price - avg_cost) / avg_cost

    # Exhaustion score: 1 - (current distance / initial cushion), clamped
    if entry_distance > 0:
        consumed = 1.0 - (distance / entry_distance)
        score = max(0.0, min(1.0, consumed))
    else:
        score = 1.0

    # Reason string
    if score >= 0.95:
        reason = "imminent_liquidation"
    elif score >= 0.75:
        reason = "high_risk"
    elif score >= 0.5:
        reason = "elevated_risk"
    elif score >= 0.25:
        reason = "moderate"
    else:
        reason = "safe"

    return {
        "exhaustion_score": round(score, 6),
        "liquidation_distance_pct": round(distance * 100, 4),
        "unrealized_pnl": round(unrealized, 4),
        "margin_ratio": round(margin_ratio, 4) if margin_ratio != float("inf") else -1.0,
        "reason": reason,
    }


# ─── Self-test fixtures ─────────────────────────────────────────────────
_SELF_TEST_FIXTURES = [
    {
        "label": "safe_long",
        "input": {
            "cash": 10000.0,
            "qty": 10,
            "avg_cost": 100.0,
            "current_price": 105.0,
            "leverage": 5,
            "side": "long",
        },
    },
    {
        "label": "boundary_long",
        "input": {
            "cash": 10000.0,
            "qty": 10,
            "avg_cost": 100.0,
            "current_price": 82.0,  # near liq for 5x long
            "leverage": 5,
            "side": "long",
        },
    },
    {
        "label": "safe_short",
        "input": {
            "cash": 10000.0,
            "qty": -10,
            "avg_cost": 100.0,
            "current_price": 95.0,
            "leverage": 5,
            "side": "short",
        },
    },
    {
        "label": "no_position",
        "input": {
            "cash": 10000.0,
            "qty": 0,
            "avg_cost": 0.0,
            "current_price": 0.0,
            "leverage": 1,
            "side": "long",
        },
    },
]


def _canonical_json(obj: Any) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def self_test() -> Dict[str, Any]:
    t0 = time.time()
    results = []
    status = "pass"
    error = None
    try:
        for fx in _SELF_TEST_FIXTURES:
            out = compute_exhaustion(**fx["input"])
            results.append({"label": fx["label"], "output": out})

        # Sanity assertions
        safe = results[0]["output"]["exhaustion_score"]
        boundary = results[1]["output"]["exhaustion_score"]
        no_pos = results[3]["output"]["exhaustion_score"]

        if not (safe < 0.5):
            raise AssertionError(f"safe fixture score {safe} should be < 0.5")
        if not (boundary > safe):
            raise AssertionError(f"boundary {boundary} should exceed safe {safe}")
        if no_pos != 0.0:
            raise AssertionError(f"no_position score {no_pos} should be 0.0")
    except Exception as e:  # noqa: BLE001
        status = "fail"
        error = f"{type(e).__name__}: {e}"

    duration_ms = int((time.time() - t0) * 1000)
    outputs = {"fixtures": results}
    return {
        "skill": SKILL_NAME,
        "version": SKILL_VERSION,
        "self_test": status,
        "fixture_hash": _sha256(_canonical_json(_SELF_TEST_FIXTURES)),
        "output_hash": _sha256(_canonical_json(outputs)),
        "outputs": outputs,
        "duration_ms": duration_ms,
        "error": error,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Margin exhaustion score")
    parser.add_argument("--self-test", action="store_true",
                        help="Run self-test, emit JSON report to stdout")
    parser.add_argument("--cash", type=float)
    parser.add_argument("--qty", type=int)
    parser.add_argument("--avg-cost", type=float)
    parser.add_argument("--current-price", type=float)
    parser.add_argument("--leverage", type=int, default=1)
    parser.add_argument("--side", type=str, choices=["long", "short"], default="long")
    parser.add_argument("--mmr", type=float, default=DEFAULT_MMR)
    args = parser.parse_args()

    if args.self_test:
        report = self_test()
        print(_canonical_json(report))
        return 0 if report["self_test"] == "pass" else 1

    if args.cash is None or args.qty is None or args.avg_cost is None or args.current_price is None:
        parser.error("cash, qty, avg-cost, current-price are required unless --self-test")

    result = compute_exhaustion(
        cash=args.cash,
        qty=args.qty,
        avg_cost=args.avg_cost,
        current_price=args.current_price,
        leverage=args.leverage,
        side=args.side,
        maintenance_margin_rate=args.mmr,
    )
    print(_canonical_json(result))
    return 0


if __name__ == "__main__":
    sys.exit(main())
