from sqlalchemy import Column, String, Float, Integer, DateTime, JSON, ForeignKey, Boolean, Text
from datetime import datetime
from ..db.base import Base
from .live_trading import generate_uuid


class AIAnalysisSchedule(Base):
    """
    User-configured schedule for periodic AI trading analysis.
    Each schedule can target specific sessions or all running sessions.
    """
    __tablename__ = "ai_analysis_schedules"

    id = Column(String, primary_key=True, default=generate_uuid)
    user_id = Column(Integer, nullable=False, index=True)
    account_id = Column(Integer, ForeignKey("exchange_accounts.id"), index=True, nullable=True)

    # Schedule Configuration
    schedule_type = Column(String, nullable=False)  # 'daily', 'weekly', 'monthly'
    schedule_time = Column(String, nullable=False, default="15:40")  # 'HH:MM' in KST
    schedule_day = Column(Integer, nullable=True)  # 1-7 for weekly (1=Mon), 1-31 for monthly, NULL for daily

    # Target
    target_sessions = Column(JSON, nullable=True)  # ["session_id1",...] or ["all_running"]

    # State
    enabled = Column(Boolean, default=True)
    last_run_at = Column(DateTime, nullable=True)
    next_run_at = Column(DateTime, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class AIAnalysisReport(Base):
    """
    Stores AI analysis reports generated by the trading-analyst Claude CLI agent.
    Each report contains trade analysis, backtest comparison, news impact, and recommendations.
    """
    __tablename__ = "ai_analysis_reports"

    id = Column(String, primary_key=True, default=generate_uuid)
    schedule_id = Column(String, ForeignKey("ai_analysis_schedules.id"), nullable=True, index=True)
    user_id = Column(Integer, nullable=False, index=True)

    # Session Context
    session_id = Column(String, ForeignKey("live_bot_sessions.id"), nullable=False, index=True)
    symbol = Column(String, nullable=False, index=True)
    strategy_name = Column(String, nullable=True)

    # Report Type
    report_type = Column(String, default="scheduled")  # 'scheduled' or 'manual'
    status = Column(String, default="pending")  # 'pending', 'running', 'completed', 'failed'

    # Input Data (snapshots for historical reference)
    trade_summary = Column(JSON, nullable=True)       # Live trading stats snapshot
    backtest_comparison = Column(JSON, nullable=True)  # Comparison data snapshot
    strategy_config = Column(JSON, nullable=True)      # Strategy params at analysis time

    # AI Analysis Result
    ai_analysis = Column(Text, nullable=True)    # Full JSON response from Claude agent
    ai_model = Column(String, nullable=True)     # e.g., "claude-sonnet-4-5-20250929"
    news_data = Column(JSON, nullable=True)      # Extracted news articles from analysis

    # Extracted Fields (for quick display without parsing full AI response)
    grade = Column(String, nullable=True)              # A, B, C, D, F
    key_findings = Column(JSON, nullable=True)         # Extracted summary/findings
    recommendations = Column(JSON, nullable=True)      # Extracted recommendation list
    risk_level = Column(String, nullable=True)         # low, medium, high
    action = Column(String, nullable=True)             # 유지, 조정, 중단

    # Notification
    telegram_sent = Column(Boolean, default=False)

    # Error
    error_message = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    completed_at = Column(DateTime, nullable=True)
