"""Add symbol_briefs table for daily Telegram brief persistence.

Stores each pre-market / post-market brief generated by
`backend/scripts/sena_daily_brief.py`. Designed to be symbol-agnostic so the
same brief script (and new ones) can reuse a single table.

Run:
    cd backend && python3 -m migrations.add_symbol_briefs

Idempotent: skips if the table already exists.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import inspect, text  # noqa: E402
from app.db.session import engine  # noqa: E402


def migrate():
    inspector = inspect(engine)
    if "symbol_briefs" in inspector.get_table_names():
        print("[SKIP] symbol_briefs already exists")
        return

    with engine.connect() as conn:
        conn.execute(text("""
            CREATE TABLE symbol_briefs (
                id                SERIAL PRIMARY KEY,
                generated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
                mode              VARCHAR(10) NOT NULL,
                symbol            VARCHAR(20) NOT NULL,
                quote             JSONB NOT NULL DEFAULT '{}'::jsonb,
                news              JSONB NOT NULL DEFAULT '[]'::jsonb,
                market_news       JSONB NOT NULL DEFAULT '[]'::jsonb,
                discussion_stats  JSONB NOT NULL DEFAULT '{}'::jsonb,
                discussion_top    JSONB NOT NULL DEFAULT '[]'::jsonb,
                disclosures       JSONB NOT NULL DEFAULT '[]'::jsonb,
                insights          JSONB NOT NULL DEFAULT '[]'::jsonb,
                raw_message       TEXT,
                telegram_sent     BOOLEAN NOT NULL DEFAULT false,
                created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
            )
        """))
        conn.execute(text(
            "CREATE INDEX idx_symbol_briefs_symbol_gen ON symbol_briefs(symbol, generated_at DESC)"
        ))
        conn.commit()
    print("[OK] symbol_briefs table created")


if __name__ == "__main__":
    migrate()
