/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tools/generate_frontend_client.py
 * Timestamp: 2026-01-09T23:30:57.688367
 */

// Utility to parse dates safely
const parseDate = (val) => {
    if (!val) return 0;
    if (typeof val === 'number') return val;
    return new Date(val).getTime() / 1000;
};

/**
 * Transformer for AccountCreate
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeAccountCreate = (data) => ({
    exchange_name: data.exchange_name,
    account_name: data.account_name,
    access_key: data.access_key,
    secret_key: data.secret_key,
    account_number: data.account_number,
});

/**
 * Transformer for AccountOut
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeAccountOut = (data) => ({
    id: data.id,
    exchange_name: data.exchange_name,
    account_name: data.account_name,
    account_number: data.account_number,
    is_active: data.is_active,
});

/**
 * Transformer for BacktestRequest
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeBacktestRequest = (data) => ({
    symbol: data.symbol,
    interval: data.interval,
    days: data.days,
    from_date: data.from_date,
    start_date: data.start_date,
    initial_capital: data.initial_capital,
    config: data.config,
});

/**
 * Transformer for Body_login_access_token_api_v1_auth_token_post
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeBody_login_access_token_api_v1_auth_token_post = (data) => ({
    grant_type: data.grant_type,
    username: data.username,
    password: data.password,
    scope: data.scope,
    client_id: data.client_id,
    client_secret: data.client_secret,
});

/**
 * Transformer for CancelOrderRequest
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeCancelOrderRequest = (data) => ({
    order_no: data.order_no,
    symbol: data.symbol,
    quantity: data.quantity,
    origin_order_no: data.origin_order_no,
});

/**
 * Transformer for ConditionalOrderRequest
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeConditionalOrderRequest = (data) => ({
    symbol: data.symbol,
    condition_type: data.condition_type,
    trigger_price: data.trigger_price,
    order_type: data.order_type,
    price_type: data.price_type,
    order_price: data.order_price,
    mode: data.mode,
    quantity: data.quantity,
    amount: data.amount,
    trailing_percent: data.trailing_percent,
});

/**
 * Transformer for FetchRequest
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeFetchRequest = (data) => ({
    interval: data.interval,
    days: data.days,
});

/**
 * Transformer for HTTPValidationError
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeHTTPValidationError = (data) => ({
    detail: data.detail,
});

/**
 * Transformer for IntegratedConfig
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeIntegratedConfig = (data) => ({
    id: data.id,
    rank: data.rank,
    config: data.config,
    strategy_id: data.strategy_id,
    symbol: data.symbol,
});

/**
 * Transformer for ManualOrderRequest
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeManualOrderRequest = (data) => ({
    symbol: data.symbol,
    order_type: data.order_type,
    price_type: data.price_type,
    price: data.price,
    mode: data.mode,
    quantity: data.quantity,
    amount: data.amount,
    percent: data.percent,
    stop_loss: data.stop_loss,
    take_profit: data.take_profit,
});

/**
 * Transformer for OptimizationRequest
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeOptimizationRequest = (data) => ({
    symbol: data.symbol,
    interval: data.interval,
    days: data.days,
    from_date: data.from_date,
    initial_capital: data.initial_capital,
    parameter_ranges: data.parameter_ranges,
    base_config: data.base_config,
});

/**
 * Transformer for OptimizationResponse
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeOptimizationResponse = (data) => ({
    strategy_id: data.strategy_id,
    best_config: data.best_config,
    results: data.results,
    failures: data.failures,
    total_combinations: data.total_combinations,
    elapsed_time: data.elapsed_time,
    task_id: data.task_id,
    status: data.status,
});

/**
 * Transformer for OptimizationResultItem
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeOptimizationResultItem = (data) => ({
    rank: data.rank,
    config: data.config,
    total_return: data.total_return,
    win_rate: data.win_rate,
    total_trades: data.total_trades,
    score: data.score,
    max_drawdown: data.max_drawdown,
    profit_factor: data.profit_factor,
    sharpe_ratio: data.sharpe_ratio,
    avg_pnl: data.avg_pnl,
    stability_score: data.stability_score,
    acceleration_score: data.acceleration_score,
    activity_rate: data.activity_rate,
    total_days: data.total_days,
    avg_holding_time: data.avg_holding_time,
    metrics: data.metrics,
});

/**
 * Transformer for OptimizationStatus
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeOptimizationStatus = (data) => ({
    task_id: data.task_id,
    status: data.status,
    progress_current: data.progress_current,
    progress_total: data.progress_total,
    message: data.message,
    result: data.result,
});

/**
 * Transformer for OrderRequest
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeOrderRequest = (data) => ({
    symbol: data.symbol,
    price: data.price,
    quantity: data.quantity,
});

/**
 * Transformer for RoleUpdate
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeRoleUpdate = (data) => ({
    is_admin: data.is_admin,
});

/**
 * Transformer for Strategy
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeStrategy = (data) => ({
    id: data.id,
    name: data.name,
    description: data.description,
    code: data.code,
    tags: data.tags,
});

/**
 * Transformer for StrategyConfig
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeStrategyConfig = (data) => ({
    tab_id: data.tab_id,
    rank: data.rank,
    is_active: data.is_active,
    tab_name: data.tab_name,
    config_json: data.config_json,
    updated_at: data.updated_at,
});

/**
 * Transformer for StrategyConfigCreate
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeStrategyConfigCreate = (data) => ({
    tab_id: data.tab_id,
    rank: data.rank,
    is_active: data.is_active,
    tab_name: data.tab_name,
    config_json: data.config_json,
});

/**
 * Transformer for StrategyResultCreate
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeStrategyResultCreate = (data) => ({
    data: data.data,
});

/**
 * Transformer for SystemModeRequest
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeSystemModeRequest = (data) => ({
    mode: data.mode,
});

/**
 * Transformer for Token
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeToken = (data) => ({
    access_token: data.access_token,
    token_type: data.token_type,
    is_admin: data.is_admin,
});

/**
 * Transformer for UserCreate
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeUserCreate = (data) => ({
    email: data.email,
    password: data.password,
});

/**
 * Transformer for UserOut
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeUserOut = (data) => ({
    id: data.id,
    email: data.email,
    is_admin: data.is_admin,
});

/**
 * Transformer for ValidationError
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeValidationError = (data) => ({
    loc: data.loc,
    msg: data.msg,
    type: data.type,
});

/**
 * Transformer for app__api__mock_strategies__IntegratedBacktestRequest__1
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeapp__api__mock_strategies__IntegratedBacktestRequest__1 = (data) => ({
    symbol: data.symbol,
    interval: data.interval,
    days: data.days,
    from_date: data.from_date,
    initial_capital: data.initial_capital,
    configs: data.configs,
});

/**
 * Transformer for app__api__mock_strategies__IntegratedBacktestRequest__2
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeapp__api__mock_strategies__IntegratedBacktestRequest__2 = (data) => ({
    configs: data.configs,
    symbol: data.symbol,
    interval: data.interval,
    days: data.days,
    from_date: data.from_date,
    initial_capital: data.initial_capital,
});

/**
 * Transformer for Candle
 * @param {Object} data - Raw API response
 * @returns {Object} Normalized for UI
 */
export const normalizeCandle = (data) => ({
    time: parseDate(data.timestamp), // Auto-mapped from timestamp
    original_timestamp: data.timestamp,
    open: data.open,
    high: data.high,
    low: data.low,
    close: data.close,
    volume: data.volume,
});
